Calculator/urls.py
from django.conf.urls import url
from . import views

app_name = "Calculator"

urlpatterns = [
    url(r'^(?P<client>[0-2])/$', views.index, name='index'),
    url(r'^register$', views.user_register, name='register'),
    url(r'^$', views.user_login, name='login'),
    url(r'^logout$', views.user_logout, name='logout'),
    url(r'^accept$', views.user_accept, name='accept'),
    url(r'^type$', views.user_type, name='type'),
    url(r'^chart$', views.user_chart, name='chart'),
    url(r'^questionnaire/(?P<key>.+)/$', views.user_questionnaire, name='questionnaire'),
    url(r'^email_address$', views.user_email_address, name = 'email_address'),
    url(r'^reset_password/(?P<key>.+)/$', views.user_reset_password, name = 'reset_password'),
    url(r'^error$', views.user_error, name = 'user_error'),
    url(r'^webinar_menu$', views.webinar_menu, name = 'webinar_menu'),
    url(r'^home$', views.return_index, name='return_index'),
    url(r'^infor$', views.user_infor, name='user_infor'),
    url(r'^news$', views.economic_news, name='news'),
    url(r'^plan$', views.user_plan, name='plan'),
    
    #url(r'^webinar$', views.webinar, name = 'webinar'),
    
    #url(r'^questionnaire$', views.user_questionnaire, name='questionnaire'),
    
               #url(r'^(?P<id>[0-9]+)/$', , name='detail'),
               
               # url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
]

Fyinance/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Calculator/',include('Calculator.urls')),
]

Calculator/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Variables

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	
	class Meta:
		model = User
		fields = ['username', 'password']


class VariablesForm(forms.ModelForm):

    class Meta:
        model = Variables
        fields = [  'monthly_income',
                    'monthly_extra_income',
                    'monthly_savings',
                  
                    'goal_income',
              			'years_to_achieve',

              			'personal_income', 
              			'family_income', 
              			'other_income',

              			'house_rent',
              			'house_utility',
              			'house_misc',

              			'car_rent',
              			'car_miles',
              			'car_insurance',

              			'phone_rent',
              			'phone_usage',
              			'phone_insurance',

              			'cable_rent',
              			'cable_speed',
              			'cable_space',

              			'phone_subscriptions',
              			'computer_subscriptions',
      					    'other_subscriptions',
              			
              			'medical_loan',
              			'car_loan',
              			'college_loan',
              			'house_loan',
              			'credit_card_loan',
              			'misc_loan',

              			'family_expenses',
              			'medical_expenses',
              			'dental_expenses',
              			'college_expenses',
              			'grocery_expenses',
              			'cloth_expesnses',
              			'life_insurance_expenses',
              			'misc_expenses'
        			]

class VariablesFormOne(forms.ModelForm):

    class Meta:
        model = Variables
        fields = [  'monthly_income',
                    'monthly_extra_income',
                    'monthly_savings',
                  
                    'goal_income',
                    'years_to_achieve',

                    'personal_income', 
                    'family_income', 
                    'other_income',

                    'house_rent',
                    'house_utility',
                    'house_misc',

                    'car_rent',
                    'car_miles',
                    'car_insurance',

                    'phone_rent',
                    'phone_usage',
                    'phone_insurance',

                    'cable_rent',
                    'cable_speed',
                    'cable_space'
              ]

class VariablesFormTwo(forms.ModelForm):

    class Meta:
        model = Variables
        fields = [  'monthly_income',
                    'monthly_extra_income',
                    'monthly_savings',
                  
                    'goal_income',
                    'years_to_achieve',

                    'personal_income', 
                    'family_income', 
                    'other_income',

                    'house_rent',
                    'house_utility',
                    'house_misc',

                    'car_rent',
                    'car_miles',
                    'car_insurance',

                    'phone_rent',
                    'phone_usage',
                    'phone_insurance',

                    'cable_rent',
                    'cable_speed',
                    'cable_space',

                    'phone_subscriptions',
                    'computer_subscriptions',
                    'other_subscriptions',
                    
                    'medical_loan',
                    'car_loan',
                    'college_loan',
                    'house_loan',
                    'credit_card_loan',
                    'misc_loan'
              ]



class ExpensesForm(forms.ModelForm):
    
    class Meta:
        model = Variables
        fields = [
                  'house_rent',
                  'house_utility',
                  'house_misc',
                  
                  'car_rent',
                  'car_insurance',
                  
                  'phone_rent',
                  'phone_insurance',
                  
                  'cable_rent',
                  
                  'phone_subscriptions',
                  'computer_subscriptions',
                  'other_subscriptions',
                  
                  'medical_loan',
                  'car_loan',
                  'college_loan',
                  'house_loan',
                  'credit_card_loan',
                  'misc_loan',
                  
                  'family_expenses',
                  'medical_expenses',
                  'dental_expenses',
                  'college_expenses',
                  'grocery_expenses',
                  'cloth_expesnses',
                  'life_insurance_expenses',
                  'misc_expenses'
                  ]

Calculator/views.py
import hashlib #, random, string
import datetime, calendar
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views import generic
from django.views.generic import View
from django.utils.crypto import get_random_string
from .models import Variables, Webinars, News, Evaluations
from .forms import UserForm, VariablesForm, ExpensesForm, VariablesFormOne, VariablesFormTwo


def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username', "")
        password = request.POST.get('password', "")
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
	            login(request, user)

	            try:
	                variables = Variables.objects.get(user=request.user)
	            except(ObjectDoesNotExist):
	                User.objects.get(username=username).delete()
	                return user_register(request)
	            if variables.enabled == True:
	            	#random_key_adder = ''.join(random.SystemRandom().choice(string.ascii_uppercase + string.digits) for i in range(10))
	            	#variables.key = random_key_adder + variables.key
	            	variables.key = generate_key(username)
	            	variables.save()
	            	return index(request, variables.client_type)
	            return render(request, 'Calculator/questionnaire.html', {"key" : variables.key})
            return render(request, 'Calculator/login.html', {'error_message': 'Your account has been disabled'})
        return render(request, 'Calculator/login.html', {'error_message': 'Invalid login'})
    return render(request, 'Calculator/login.html')


def user_email_address(request):
    if request.method == "POST":
        email = request.POST.get('email_address', "")

        #check for username
        try:
	        user = User.objects.get(username=email)
        except(ObjectDoesNotExist): 
        	return render(request, 'Calculator/error.html')

        try:        
           	variables = Variables.objects.get(user=user)
        except Variables.DoesNotExist:
            variables = Variables(user=user)
            variables.save()

        key = variables.key
        subject = 'Change Password'
        message = 'Please click to change password: http://127.0.0.1:8000/Calculator/reset_password/'+str(key)
        from_email = settings.EMAIL_HOST_USER
        to_list = [email]
        send_mail(subject, message, from_email, to_list, fail_silently=False)

        return render(request, 'Calculator/email.html')
    return render(request, 'Calculator/email_address.html')
 
def user_reset_password(request, key):	
    if request.method == "POST":
        password = request.POST.get('password', "")

        try:        
           	variables = Variables.objects.get(key=key)
        except Variables.DoesNotExist:
            return render(request, 'Calculator/error.html')

        variables.user.set_password(password)
        variables.user.save()
        return render(request, 'Calculator/login.html')
    return render(request, 'Calculator/reset_password.html', {"key": key})

def user_error(request):
	return render(request, 'Calculator/error.html')

def user_register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        
        user.set_password(password)
        user.save()

        key = generate_key(username)
        subject = 'Registration Email'
        message = 'Please click to register: http://127.0.0.1:8000/Calculator/questionnaire/'+str(key)
        from_email = settings.EMAIL_HOST_USER
        to_list = [username]
        send_mail(subject, message, from_email, to_list, fail_silently=False)

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                user = request.user
                try:        
                    variables = Variables.objects.get(user=user)
                    evaluations = Evaluations.objects.get(user=user)
                except Variables.DoesNotExist:
                    variables = Variables(user=user)
                    variables.save()
                    evaluations = Evaluations(user=user)
                    evaluations.save()
                variables.key = key
                variables.save()
                return render(request, 'Calculator/email.html')
    context = {
        "form": form,
    }
    return render(request, 'Calculator/register.html', context)


def generate_key(username):
    chars = 'abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)'
    secret_key = get_random_string(20, chars)
    return hashlib.sha256((secret_key + username).encode('utf-8')).hexdigest()


def user_questionnaire(request, key):
    if not request.user.is_authenticated():
        return render(request, "Calculator/login.html")
    user = request.user
    try:        
        variables = Variables.objects.get(user=user)
    except Variables.DoesNotExist:
        variables = Variables(user=user)
        variables.save()
    if request.method == "POST":
        variables.last_name = request.POST.get('last_name', "")
        variables.first_name = request.POST.get('first_name', "")
        variables.zip_code = request.POST.get('zip_code',10000)
        variables.phone_number = request.POST.get('phone_number', 1000000000)
        variables.age = request.POST.get('age',"2017/01/01")
        variables.sex = request.POST.get('sex', "")
        variables.martial_status = request.POST.get('martial_status', "")
        variables.education = request.POST.get('education', "")
        variables.financial_knowledge = request.POST.get('financial_knowledge', "")
        variables.boolean_bank_account = request.POST.get("boolean_bank_account", False)
        variables.boolean_car = request.POST.get("boolean_car", False)
        variables.boolean_home = request.POST.get("boolean_home", False)
        variables.boolean_children = request.POST.get("boolean_children", False)
        variables.boolean_credit_cards = request.POST.get("boolean_credit_cards", False)
        variables.boolean_college_loan = request.POST.get("boolean_college_loan", False)
        variables.boolean_medical_debt = request.POST.get("boolean_medical_debt", False)
        variables.have_job = request.POST.get("have_job", "")
        variables.work_length = request.POST.get("work_length", "")
        variables.job_title = request.POST.get("job_title", "")
        variables.mortgage_satisfaction = request.POST.get("mortgage_satisfaction", "")
        variables.mortgage_provider = request.POST.get("mortgage_provider", "")
        variables.have_car_loan = request.POST.get("have_car_loan", "")
        variables.car_loan_provider = request.POST.get("car_loan_provider", "")
        variables.car_satisfaction = request.POST.get("car_satisfaction", "")
        variables.car_insurance_satisfaction = request.POST.get("car_insurance_satisfaction", "")
        variables.car_insurance_provider =  request.POST.get("car_insurance_provider", "")
        variables.phone_length = request.POST.get("phone_length", "")
        variables.phone_provider = request.POST.get("phone_provider", "")
        variables.phone_satisfaction = request.POST.get("phone_satisfaction", "")
        variables.cable_provider = request.POST.get("cable_provider", "")
        variables.cable_satisfaction = request.POST.get("cable_satisfaction", "")
        variables.gym_provider = request.POST.get("gym_provider", "")
        variables.boolean_netflix = request.POST.get("boolean_netflix", False)
        variables.boolean_youtube_red = request.POST.get("boolean_youtube_red", False)
        variables.boolean_xbox_live = request.POST.get("boolean_xbox_live", False)
        variables.boolean_playstation_live = request.POST.get("boolean_playstation_live", False) 
        variables.boolean_wow = request.POST.get("boolean_wow", False)
        variables.boolean_lol = request.POST.get("boolean_lol", False)
        variables.health_insurance_provider = request.POST.get("health_insurance_provider", "")
        variables.health_insurance_satisfaction = request.POST.get("health_insurance_satisfaction", "")
        variables.dental_insurance_provider = request.POST.get("dental_insurance_provider", "")
        variables.dental_insurance_satisfaction = request.POST.get("dental_insurance_satisfaction", "")
        variables.student_loan_manageable = request.POST.get("student_loan_manageable", "")
        variables.car_loan_manageable = request.POST.get("car_loan_manageable", "")
        variables.mortgage_manageable = request.POST.get("mortgage_manageable", "")
        variables.change_expense_habit = request.POST.get("change_expense_habit", "")
        variables.save()
        return render(request, 'Calculator/accept.html')
    context = {
        "variables": variables,
        "key": key
        }
    return render(request, 'Calculator/questionnaire.html', context)


def user_accept(request):
    if not request.user.is_authenticated():
        return render(request, "Calculator/login.html")
    if request.method == "POST":
        accept = request.POST.get('accept', "")
        if accept == 'accept':
            user = request.user
            try:        
                variables = Variables.objects.get(user=user)
                variables.enabled = True
                variables.save()
            except Variables.DoesNotExist:

Calculator/templates/Calculator/chart.html
{% extends 'Calculator/base.html' %}

{% block body %}

<div class="container-fluid">
	<div class="row">
		
		<div class="well hero row-fluid summary-box container">
			<div class="panel panel-default">
				<div class="panel-body">
					<form  role="form" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						<fieldset>

							    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
							    <script type="text/javascript">
							    	google.charts.load('current', {'packages':['corechart']});
							    	google.charts.setOnLoadCallback(drawChart);
							    	function drawChart() {
							        	var data = google.visualization.arrayToDataTable([
								          	['Task', 'Dollars'],
								          	['house', {{house}}],
								          	['car', {{car}}],
								          	['phone', {{phone}}],
								          	['cable', {{cable}}],
								          	['subscriptions', {{subscriptions}}],
								          	['loan', {{loan}}],
								          	['expenses', {{expenses}}],
								        	]);

								        var pie_options = {
								          	title: 'Monthly Expenses Pie Chart'
								        };

							        	var pie_chart = new google.visualization.PieChart(document.getElementById('piechart'));

							        	pie_chart.draw(data, pie_options);
							    }
							    </script>

							    <div id="piechart" style="width: 650px; height: 300px;"></div>

		  						<script type="text/javascript">
								    google.charts.load("current", {packages:['corechart']});
								    google.charts.setOnLoadCallback(drawChart);
								    function drawChart() {
								      var data = google.visualization.arrayToDataTable([
								        ["Expenses", "$", { role: "style" } ],
								        ["house", {{house}}, "blue"],
								        ["car", {{car}}, "red"],
								        ["phone", {{phone}}, "orange"],
								        ["cable", {{cable}}, "green"],
						     	        ["subscriptions", {{subscriptions}}, "gold"],
								        ["loan", {{loan}}, "brown"],
								        ["expenses", {{expenses}}, "purple"]
								      ]);

								      var view = new google.visualization.DataView(data);
								      view.setColumns([0, 1,
								                       { calc: "stringify",
								                         sourceColumn: 1,
								                         type: "string",
								                         role: "annotation" },
								                       2]);

								      var options = {
								        title: "Monthly Expenses Column Chart",
								        width: 650,
								        height: 300,
								        bar: {groupWidth: "95%"},
								        legend: { position: "none" },
								      };
								      var chart = new google.visualization.ColumnChart(document.getElementById("columnchart_values"));
								      chart.draw(view, options);
								  }
	 						    </script>
								<div id="columnchart_values" style="width: 650px; height: 300px;"></div>


								<script>
								      google.charts.load('current', {'packages':['corechart']});
								      google.charts.setOnLoadCallback(drawChart);

								      function drawChart() {
								        var data = google.visualization.arrayToDataTable([
								          ['Month', 'Savings'],
								          ['1',  {{savings}} ],
								          ['2',  {{savings}}*2 ],
								          ['3',  {{savings}}*3 ],
								          ['4',  {{savings}}*4 ], 
								          ['5',  {{savings}}*5 ], 
								          ['6',  {{savings}}*6 ], 
								          ['7',  {{savings}}*7 ], 
								          ['8',  {{savings}}*8 ], 
								          ['9',  {{savings}}*9 ], 
								          ['10', {{savings}}*10], 
								          ['11', {{savings}}*11], 
								          ['12', {{savings}}*12], 
								        ]);

								        var options = {
								          title: 'Yearly Savings Increment Line Chart I',
								          curveType: 'function',
								          legend: { position: 'bottom' }
								        };

								        var chart = new google.visualization.LineChart(document.getElementById('curve_chart_I'));

								        chart.draw(data, options);
								      }
								</script>
 								<div id="curve_chart_I" style="width: 650px; height: 300px;"></div>

 								<script>
								      google.charts.load('current', {'packages':['corechart']});
								      google.charts.setOnLoadCallback(drawChart);

								      function drawChart() {
								        var data = google.visualization.arrayToDataTable([
								          ['Savings', 'Month'],
								          ['{{savings}}', 1], 
								          [{{savings}}*2, 2], 
								          [{{savings}}*3, 3], 
								          [{{savings}}*4, 4], 
								          [{{savings}}*5, 5], 
								          [{{savings}}*6, 6], 
								          [{{savings}}*7, 7], 
								          [{{savings}}*8, 8], 
								          [{{savings}}*9, 9], 
								          [{{savings}}*10, 10], 
								          [{{savings}}*11, 11], 
								          [{{savings}}*12, 12], 
								        ]);

								        var options = {
								          title: 'Yearly Savings Increment Line Chart II',
								          curveType: 'function',
								          legend: { position: 'bottom' }
								        };

								        var chart = new google.visualization.LineChart(document.getElementById('curve_chart_II'));

								        chart.draw(data, options);
								      }
								</script>
 								<div id="curve_chart_II" style="width: 650px; height: 300px;"></div>

	<!--
							<script type="text/javascript">
							google.charts.load('current', {packages: ['corechart', 'bar']});
							google.charts.setOnLoadCallback(drawBasic);

							function drawBasic() {

							      var data = new google.visualization.DataTable();
							      data.addColumn('timeofday', 'Types of Expenses');
							      data.addColumn('number', '$');

							      data.addRows([
							        [{v: [8, 0, 0], f: 'house'}, 1],
							        [{v: [9, 0, 0], f: 'car'}, 2],
							        [{v: [10, 0, 0], f:'10 am'}, 3],
							        [{v: [11, 0, 0], f: '11 am'}, 4],
							        [{v: [12, 0, 0], f: '12 pm'}, 5],
							        [{v: [13, 0, 0], f: '1 pm'}, 6],
							        [{v: [14, 0, 0], f: '2 pm'}, 7],
							        [{v: [15, 0, 0], f: '3 pm'}, 8],
							        [{v: [16, 0, 0], f: '4 pm'}, 9],
							        [{v: [17, 0, 0], f: '5 pm'}, 10],
							      ]);

							      var options = {
							        title: 'Monthly Expenses Column Chart',
							        hAxis: {
							          title: 'Types of Expenses',
							          format: 'h:mm a',
							          viewWindow: {
							            min: [7, 30, 0],
							            max: [17, 30, 0]
							          }
							        },
							        vAxis: {
							          title: 'Dollars'
							        }
							      };

							      var chart = new google.visualization.ColumnChart(
							        document.getElementById('chart_div'));

							      chart.draw(data, options);
							    }
							</script>
	  						<div id="chart_div"></div>
-->
						</fieldset>

						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<a href="{% url 'Calculator:index' client %}" type="button" class="btn btn-primary"> Back to Calculator </a>
								<br><br>
								<a href="{% url 'Calculator:logout' %}" type="button" class="btn btn-danger"> logout </a>
							</div>
						</div>

					</form>
				</div>
			</div>
		
	</div>
</div>

{% endblock %}

Calculator/templates/Calculator/email.html
{% extends 'Calculator/base.html' %}

{% block body %}

{% load getattribute %}

<div class="container-fluid">
	<div class="row">
		<div class="well hero row-fluid summary-box container">
			<div class="panel panel-default">
				<div class="panel-body">
					<h4>Please check your email</h4>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

Calculator/templates/Calculator/email_address.html
{% extends 'Calculator/base.html' %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="well hero row-fluid summary-box container">
                <div class="panel panel-primary">
                <div class="panel-heading">
                <h3 class="panel-title" > <h4>User Email</h4> </h3>
                </div>
                <div class="panel-body">
                    
                    <form class="form-horizontal" role="form" action="{% url 'Calculator:email_address' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="email_address">Email Address:</label>
                            <div class="col-sm-10">
                                <input id="email_address" maxlength="30" name="email_address" type="email">
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary">Send Email</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Back to login? <a href="{% url 'Calculator:login' %}">Click here</a> to go back.
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

Calculator/templates/Calculator/error.html
{% extends 'Calculator/base.html' %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="well hero row-fluid summary-box container">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h4>User Does not Exist</h4>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'Calculator:register' %}">Click here</a> to register.
    </div>
            </div> 
        </div>
    </div>
     
</div>
{% endblock %}

Calculator/templates/Calculator/login.html
{% extends 'Calculator/base.html' %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="well hero row-fluid summary-box container">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <h4> Log into Fyinance </h4>
                    </h3>
                </div>
                <div class="panel-body">
               
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'Calculator:login' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">Email Address:</label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">Password:</label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary">Login</button>
                            </div>
                        </div>
                    </form>
                </div>

                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'Calculator:register' %}">Click here</a> to register.
                </div>

                <div class="panel-footer">
                    Forget your password? <a href="{% url 'Calculator:email_address' %}">Click here</a> to reset password.
                </div>

            </div>
        </div>
    </div>

</div>
{% endblock %}

Calculator/templates/Calculator/webinar.html
{% extends 'Calculator/base.html' %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="well hero row-fluid summary-box container">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'Calculator:login' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">Email Address:</label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">Password:</label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary">Login</button>
                            </div>
                        </div>
                    </form>
                </div>

                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'Calculator:register' %}">Click here</a> to register.
                </div>

                <div class="panel-footer">
                    Forget your password? <a href="{% url 'Calculator:email_address' %}">Click here</a> to reset password.
                </div>

            </div>
        </div>
    </div>

</div>
{% endblock %}